common/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView

from . import views

app_name = 'common'

urlpatterns = [
    path('', views.home, name='home'),
    path('order/', views.order, name='order'),
    path('queue/', views.queue, name='queue'),
    path('washing/', views.washing, name='washing'),
    path('settings/', views.settings, name='settings'),
    path('login/', views.MyLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout')
]


core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('common.urls', namespace='common')),
    path('admin/', admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


common/models.py
from django.db import models

# Create your models here.

common/views.py
from django.shortcuts import render
from django.contrib.auth.views import LoginView
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth.decorators import user_passes_test



class MyLoginView(LoginView):
    redirect_authenticated_user = True
    success_url = '/' 
    template_name = 'login.html'
    
    def form_invalid(self, form):
        messages.error(self.request, 'Natogri login yoki parol')
        return self.render_to_response(self.get_context_data(form=form))


@user_passes_test(lambda u: u.is_superuser)
def home(request):
    return render(request, 'index.html')

@user_passes_test(lambda u: u.is_superuser)
def order(request):
    return render(request, 'order_list.html')

@user_passes_test(lambda u: u.is_superuser)
def queue(request):
    return render(request, 'navbat.html')

@user_passes_test(lambda u: u.is_superuser)
def washing(request):
    return render(request, 'washing.html')

@user_passes_test(lambda u: u.is_superuser)
def settings(request):
    return render(request, 'settings.html')

templates/index.html
{% extends 'wrapper.html' %}
{% load static %}

{% block page %}Bosh sahifa{% endblock page %}
{% block title %}Bosh sahifa{% endblock title %}

{% block content %}
    <div class="main-hero_info_wrapper">
        <ul class="main-hero_list">
            <li class="main-hero_item_blue vanilla-item" data-tilt data-tilt-scale="1.1">
                <img src="{% static 'assets/image/money-recive.png' %}" alt="">
                <p class="main-hero_title">
                    Kirim
                </p>
                <p class="main-hero_money">
                    +0 UZS
                </p>
            </li>
            <li class="main-hero_item_yellow vanilla-item" data-tilt data-tilt-scale="1.1">
                <img src="{% static 'assets/image/money-send.png' %}" alt="">
                <p class="main-hero_title">
                    Chiqim
                </p>
                <p class="main-hero_money">
                    -0 UZS
                </p>
            </li>
            <li class="main-hero_item_blue vanilla-item" data-tilt data-tilt-scale="1.1">
                <img src="{% static 'assets/image/car.png' %}" alt="">
                <p class="main-hero_title">
                    Navbat
                </p>
                <p class="main-hero_count">
                    0 ta
                </p>
            </li>
            <li class="main-hero_item_yellow vanilla-item" data-tilt data-tilt-scale="1.1">
                <img src="{% static 'assets/image/car-washing.png' %}" alt="">
                <p class="main-hero_title">
                    Yuvilmoqda
                </p>
                <p class="main-hero_count">
                    0 ta
                </p>
            </li>
        </ul>
        <ul class="main-hero_weather_app">
            <li class="main-hero_weather_app_item">
                <h1 class="main-hero_weather_heading" style="text-align:center;">Bugun</h1>
            </li>
            <li>
                <h1 style="color:white;text-align:center;margin-top:50px">Malumotlar topilmadi</h1>
            </li>
        </ul>
    </div>
{% endblock content %}

templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta property="og:type" content="website">
    <meta property="og:url" content="https://carwash.binokor-asaka.uz/">
    <meta property="og:title" content="Car Wash">
    <meta property="og:description" content="Simple CRM System for CarWash">
    <meta property="og:image"
        content="https://metatags.io/assets/meta-tags-16a33a6a8531e519cc0936fbba0ad904e52d35f34a46c97a2c9f6f7dd7d336f2.png">

    <!-- links -->
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/responsive.css' %}">
    <link rel="stylesheet" href="https://site-assets.fontawesome.com/releases/v6.3.0/css/all.css">
    <title>Login Car Wash</title>
</head>

<body>
    <div class="login-hero">
        <div class="section-wrapp">
            <div class="login-container">
                <ul class="login-hero_list">
                    <li class="login-hero_item">
                        <img src="{% static 'assets/image/car-login.png' %}" class="login-hero_image" alt="">
                    </li>
                    <li class="login-hero_item">
                        <form method="post" class="login-hero_form">
                            {% csrf_token %}
                            <h1 class="login-hero_form_heading">
                                Kirish
                            </h1>
                            <p class="login-hero_form_text">
                                Tizimga kirish uchun login va parolingizni kiriting
                            </p>
                            <input type="text" name="username" placeholder="User name">
                            <input type="password" name="password" placeholder="Parol">
                            <div class="login-hero_form_btn_wrapper">
                                <button class="login-hero_form_btn">Kirish</button>
                            </div>
                        </form>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <script src="{% static 'assets/js/login.js' %}"></script>
</body>

</html>

templates/logout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta property="og:type" content="website">
    <meta property="og:url" content="https://metatags.io/">
    <meta property="og:title" content="Car Wash">
    <meta property="og:description" content="description here">
    <meta property="og:image"
        content="https://metatags.io/assets/meta-tags-16a33a6a8531e519cc0936fbba0ad904e52d35f34a46c97a2c9f6f7dd7d336f2.png">

    <!-- links -->
    <link rel="stylesheet" href="./assets/css/style.css">
    <link rel="stylesheet" href="./assets/css/responsive.css">
    <link rel="stylesheet" href="https://site-assets.fontawesome.com/releases/v6.3.0/css/all.css">
    <title>Logout Car Wash</title>
</head>

<body>
    <div class="login-hero">
        <div class="section-wrapp">
            <div class="login-container">
                <ul class="login-hero_list">
                    <li class="login-hero_item">
                        <img src="./assets/image/car-login.png" class="login-hero_image changed" alt="">
                    </li>
                    <li class="login-hero_item">
                        <form action="" class="login-hero_form">
                            <h1 class="login-hero_form_heading">
                                Chikib ketildi!
                            </h1>
                            <p class="login-hero_form_text">
                                Tizimga qayta kirish uchun shu yerga <a class="logout-hero_form_link"
                                    href="./login.html">bosing</a>
                            </p>
                        </form>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <script src="./assets/js/logout.js"></script>
</body>

</html>

templates/navbat.html
{% extends 'wrapper.html' %}
{% block title %}Navbatlar{% endblock %}
{% block page %}Navbatlar{% endblock %}
{% block content %}
<center>
    <br>
    <br>
    <br>
    <h1>
        Hozircha navbatlar yo'q
    </h1>
</center>
<!-- <ul class="navbat-hero_main_list">
    <li class="navbat-hero_main_item">
        <ul class="navbat-hero_inner_list">
            <li class="navbat-hero_inner_item_number">
                <a href="#">
                    #1
                </a>
            </li>
            <li class="navbat-hero_inner_item_photo navbat-hero_inner_item">
                <a href="#">
                    <img src="./assets/image/gentra.png" alt="">
                </a>
            </li>
            <li class="navbat-hero_inner_item_name navbat-hero_inner_item">
                <a href="#">
                    Gentra
                </a>
            </li>
            <li class="navbat-hero_inner_item_mark navbat-hero_inner_item">
                <a href="#">
                    <img src="./assets/image/chevrolet-logo.png" alt="">
                </a>
            </li>
            <li class="navbat-hero_inner_item_color navbat-hero_inner_item">
                <a href="#">
                    Oq
                </a>
            </li>
            <li class="navbat-hero_inner_item_type navbat-hero_inner_item">
                <a href="#">
                    Oddiy
                </a>
            </li>
            <li class="navbat-hero_inner_item_cost navbat-hero_inner_item">
                <a href="#">
                    40 000 UZS
                </a>
            </li>
        </ul>
    </li>
</ul> -->
{% endblock %}

templates/navbat_detail.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta property="og:type" content="website">
    <meta property="og:url" content="https://metatags.io/">
    <meta property="og:title" content="Car Wash">
    <meta property="og:description" content="description here">
    <meta property="og:image"
        content="https://metatags.io/assets/meta-tags-16a33a6a8531e519cc0936fbba0ad904e52d35f34a46c97a2c9f6f7dd7d336f2.png">

    <!-- links -->
    <link rel="stylesheet" href="./assets/css/style.css">
    <link rel="stylesheet" href="./assets/css/responsive.css">
    <link rel="stylesheet" href="https://site-assets.fontawesome.com/releases/v6.3.0/css/all.css">
    <title>Car Wash | Buyurtma berish</title>
</head>

<body>
    <header>
        <div class="section-wrapp">
            <div class="container">
                <div class="header-top_wrapper">
                    <h1 class="main-header_title">
                        Navbat
                    </h1>
                    <div class="header-info_wrapper">
                        <div class="header-info_item_wrapper">
                            <i class="fa-solid fa-clock"></i>
                            <span class="header-time_info"></span>
                        </div>
                        <div class="header-info_item_wrapper">
                            <i class="fa-solid fa-calendar-days"></i>
                            <span class="header-date_info"></span>
                        </div>
                        <div class="header-info_item_wrapper">
                            <i class="fa-solid fa-clouds"></i>
                            <span class="booked-wzs-day-number">22°</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="header-side_bar_wrapper">
            <div class="header-side_bar">
                <nav class="header_navigation">
                    <ul class="nav_items_wrapper">
                        <li class="nav_item selected"><i class="fa-solid fa-house"></i></li>
                        <li class="nav_item"><i class="fa-solid fa-square-plus"></i></li>
                        <li class="nav_item"><i class="fa-solid fa-car-mirrors"></i></li>
                        <li class="nav_item"><i class="fa-solid fa-car-wash"></i></li>
                        <li class="nav_item"><i class="fa-solid fa-square-dollar"></i></li>
                        <li class="nav_item nav_item_last"><i class="fa-duotone fa-gear"></i></li>
                        <li class="nav_item_helper"></li>
                    </ul>
                </nav>
                <div class="nav_bg"></div>
            </div>
        </div>
    </header>
    <main>
        <div class="order-list">
            <div class="section-wrapp">
                <div class="container">
                    <ul class="order-detail_list">
                        <form action="" class="order-form">
                            <li class="order-detail_item">
                                <h1 class="order-detail_heading">
                                    Mashina
                                </h1>
                                <select name="car_mark" id="">
                                    <option value="" style="display: none;">Markani tanlang</option>
                                    <option value="chevrolet" selected>Chevrolet</option>
                                    <option value="deawo">Deawo</option>
                                </select>
                                <select name="car_model" id="">
                                    <option value="" style="display: none;">Modelni tanlang</option>
                                    <option value="chevrolet" selected>Malibu</option>
                                    <option value="deawo">Deawo</option>
                                </select>
                                <select name="car_color" id="">
                                    <option value="" style="display: none;">Rangni tanlang</option>
                                    <option value="chevrolet" selected>oq</option>
                                    <option value="deawo">qora</option>
                                </select>
                                <input type="text" placeholder="Davlat raqami" class="order-car_number"
                                    name="car_number" value="A 615 KA">
                                <input type="text" placeholder="Telefon raqami" class="order-tel_number"
                                    name="tel_number" value="+998 90 123 45 67">
                                <textarea name="car_comment" class="order-car_comment">Tezroq bolsin</textarea>
                            </li>
                            <li class="order-detail_item">
                                <h1 class="order-detail_heading">
                                    Xizmatlar
                                </h1>
                                <select name="car_mark" id="" class="order-car_wash_type premium">
                                    <option value="" style="display: none;">Yuvish turi</option>
                                    <option value="oddiy">Oddiy</option>
                                    <option value="premium">Premium</option>
                                </select>
                                <div class="order-detail_checkboxes">
                                    <input type="checkbox" name="chang_yutgich" id="chang_yutgich">
                                    <label for="chang_yutgich">Chang yutgich</label>
                                    <input type="checkbox" name="chang_yutgich2" id="chang_yutgich2">
                                    <label for="chang_yutgich2">Ko‘pirtirgich</label>
                                    <input type="checkbox" name="chang_yutgich3" id="chang_yutgich3">
                                    <label for="chang_yutgich3">Hushbo‘ylik</label>
                                    <input type="checkbox" name="chang_yutgich4" id="chang_yutgich4">
                                    <label for="chang_yutgich4">Chang yutgich</label>
                                    <input type="checkbox" name="chang_yutgich5" id="chang_yutgich5">
                                    <label for="chang_yutgich5">Ko‘pirtirgich</label>
                                    <input type="checkbox" name="chang_yutgich6" id="chang_yutgich6">
                                    <label for="chang_yutgich6">Hushbo‘ylik</label>
                                </div>
                            </li>
                            <li class="order-detail_item_info">
                                <h1 class="order-detail_heading">
                                    Ma’lumotlar
                                </h1>
                                <div class="order-detail_info_wrapp">
                                    <img class="order-detail_info_car" src="./assets/image/malibu.png" alt="">
                                    <div class="order-detail_car_subinfo">
                                        <img src="./assets/image/chevrolet-logo.png" alt="">
                                        Malibu oq
                                    </div>
                                    <div class="order-detail_car_subinfo_number">
                                        <div class="order-detail_car_number">
                                            <span>60</span>
                                            <span class="order-detail_car_number_info">A 123 NN</span>
                                        </div>
                                        <div class="order-detail_customer_number">
                                            +998331011747
                                        </div>
                                    </div>
                                    <select name="yuvish_yolagi" id="" class="navbat-detail_selection">
                                        <option value="Yuvish_yolagi" style="display: none;" selected>Yuvish yo‘lagi
                                        </option>
                                        <option value="1">1</option>
                                        <option value="2">2</option>
                                        <option value="3">3</option>
                                        <option value="4">4</option>
                                        <option value="5">5</option>
                                    </select>
                                    <select name="yuvish_yolagi" id="" class="navbat-detail_selection">
                                        <option value="Ishchi" selected style="display: none;">Ishchi</option>
                                        <option value="John_doe">John Doe</option>
                                        <option value="John_doe">John Doe</option>
                                        <option value="John_doe">John Doe</option>
                                        <option value="John_doe">John Doe</option>
                                        <option value="John_doe">John Doe</option>
                                        <option value="John_doe">John Doe</option>
                                    </select>
                                    <p class="order-detail_total_qty">
                                        Narxi: 40 000 UZS
                                    </p>
                                    <div class="order-detail_buy">
                                        <button class="order-detail_buy_btn" type="">Navbatga olish</button>
                                    </div>
                                </div>
                            </li>
                        </form>
                    </ul>
                </div>
            </div>
        </div>
    </main>
    <footer>
        <div class="section-wrapp">
            <div class="container">
                <ul class="footer-list">
                    <li class="footer-item">
                        Copyright © 2023. CarWash. All rights reserved.
                    </li>
                    <li class="footer-item">
                        <ul class="footer-inner_list">
                            <li class="footer-inner_item">
                                <a href="#">
                                    <i class="fa-brands fa-facebook-f"></i>
                                </a>
                            </li>
                            <li class="footer-inner_item">
                                <a href="#">
                                    <i class="fa-brands fa-instagram"></i>
                                </a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </footer>
    <script src="./assets/js/navbat_detail.js"></script>
</body>

</html>

templates/wrapper.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <meta property="og:type" content="website">
    <meta property="og:url" content="https://carwash.binokor-asaka.uz/">
    <meta property="og:title" content="Car Wash">
    <meta property="og:description" content="Simple CRM System for Car Wash">
    <meta property="og:image"
        content="https://metatags.io/assets/meta-tags-16a33a6a8531e519cc0936fbba0ad904e52d35f34a46c97a2c9f6f7dd7d336f2.png">

    <!-- links -->
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/responsive.css' %}">
    <link rel="stylesheet" href="https://site-assets.fontawesome.com/releases/v6.3.0/css/all.css">

    <title>Car Wash | {% block title %}{% endblock title %}</title>
</head>

<body>
    <header>
        <div class="section-wrapp">
            <div class="container">
                <div class="header-top_wrapper">
                    <h1 class="main-header_title">
                        {% block page %}{% endblock page %}
                    </h1>
                    <div class="header-info_wrapper">
                        <div class="header-info_item_wrapper">
                            <i class="fa-solid fa-clock"></i>
                            <span class="header-time_info"></span>
                        </div>
                        <div class="header-info_item_wrapper">
                            <i class="fa-solid fa-calendar-days"></i>
                            <span class="header-date_info"></span>
                        </div>
                        <div class="header-info_item_wrapper">
                            <i class="fa-solid fa-clouds"></i>
                            <span class="booked-wzs-day-number">Topilmadi°</span>
                        </div>
                        <div class="header-info_item_wrapper">
                            <a href="{% url 'common:logout' %}" class="order-detail_buy_btn">Chiqish</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="header-side_bar_wrapper">
            <div class="header-side_bar">
                <nav class="header_navigation">
                    <ul class="nav_items_wrapper">
                        <li class="nav_item selected">
                            <a class="nav-link" href="{% url 'common:home' %}"><i class="fa-solid fa-house"></i></a>
                        </li>
                        <li class="nav_item">
                            <a class="nav-link" href="{% url 'common:order' %}"><i class="fa-solid fa-square-plus"></i></a>
                        </li>
                        <li class="nav_item">
                            <a class="nav-link" href="{% url 'common:queue' %}"><i class="fa-solid fa-car-mirrors"></i></a>
                        </li>
                        <li class="nav_item">
                            <a class="nav-link" href="{% url 'common:washing' %}"><i class="fa-solid fa-car-wash"></i></a>
                        </li>
                        <li class="nav_item">
                            <a><i class="fa-solid fa-square-dollar"></i></a>
                        </li>
                        <li class="nav_item nav_item_last">
                            <a class="nav-link" href="{% url 'common:settings' %}"><i class="fa-duotone fa-gear"></i></a>
                        </li>
                        <li class="nav_item_helper"></li>
                    </ul>
                </nav>
                <div class="nav_bg"></div>
            </div>
        </div>
    </header>
    <main>
        <div class="main-hero">
            <div class="section-wrapp">
                <div class="container">
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </main>
    <footer>
        <div class="section-wrapp">
            <div class="container">
                <ul class="footer-list">
                    <li class="footer-item">
                        Copyright © 2023. CarWash. All rights reserved.
                    </li>
                    <li class="footer-item">
                        <ul class="footer-inner_list">
                            <li class="footer-inner_item">
                                <a href="#">
                                    <i class="fa-brands fa-facebook-f"></i>
                                </a>
                            </li>
                            <li class="footer-inner_item">
                                <a href="#">
                                    <i class="fa-brands fa-instagram"></i>
                                </a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </footer>
    <script src="{% static 'assets/js/vanilla-tilt_settings.js' %}">
    </script>
    <script src="{% static 'assets/js/vanilla-tilt.min.js' %}"></script>
    <script src="{% static 'assets/js/main.js' %}"></script>
    <script>
        var navLinks = document.querySelectorAll('.nav-link');
        navLinks.forEach((e) => {
            if (e.pathname === window.location.pathname) {
                e.parentElement.classList.add('selected');
            } else {
                e.parentElement.classList.remove('selected')
            }
        })
    </script>
    {% block script %}
    {% endblock %}
</body>

</html>